// GENERATED FILE, DO NOT MODIFY! YOUR MODIFICATION WILL BE LOST!
package ${e.packageOfJavaModel}.${e.database.name};

import java.sql.Timestamp;
import java.math.BigDecimal;

/**
 * ${t.javaName}.
 * <br>${t.comment}
 * <br>Generated from ${t.dbName} database table.
 * <br>Created on: ${e.database.modelCreationDate}
 * <br>Database name: ${e.database.name}
 * <br>Generated by ${appname} v${appversion}
 */
public class ${t.javaName} implements hu.vanio.easydao.core.Model, java.io.Serializable {

    <#list t.fieldList as field>
    /* ${field.comment}. Database: ${field.dbName}, ${field.dbType}, <#if field.primaryKey>primary key, </#if><#if field.nullable>not nullable.<#else>nullable.</#if> */
    private <#if field.javaTypeAsString == 'Clob'>String<#elseif field.javaTypeAsString == 'Blob'>Byte[]<#else>${field.javaTypeAsString}</#if> ${field.javaName};
    </#list>

    /** Default constructor. */
    public ${t.javaName}() {}

    /**
     * Constructor.
    <#list t.fieldList as field>
     * @param ${field.javaName} ${field.comment}
    </#list>
     */
    public ${t.javaName}(<#list t.fieldList as field><#if field.javaTypeAsString == 'Clob'>String<#elseif field.javaTypeAsString == 'Blob'>Byte[]<#else>${field.javaTypeAsString}</#if> ${field.javaName}<#if field_has_next>, </#if></#list>) {
        <#list t.fieldList as field>
        this.${field.javaName} = ${field.javaName};
        </#list>
    }

    <#list t.fieldList as field>
    /**
     * ${field.comment}
     * <br>${field.dbName}, ${field.dbType}, <#if field.primaryKey>primary key, </#if><#if field.nullable>not nullable.<#else>nullable.</#if>
     * @return ${field.comment}
     */
    public <#if field.javaTypeAsString == 'Clob'>String<#elseif field.javaTypeAsString == 'Blob'>Byte[]<#else>${field.javaTypeAsString}</#if> get${field.javaName?cap_first}() {
        return this.${field.javaName};
    }
    
    /**
     * ${field.comment}
     * <br>${field.dbName}, ${field.dbType}, <#if field.primaryKey>primary key, </#if><#if field.nullable>not nullable.<#else>nullable.</#if>
     * @param ${field.javaName} ${field.comment}
     */
    public void set${field.javaName?cap_first}(<#if field.javaTypeAsString == 'Clob'>String<#elseif field.javaTypeAsString == 'Blob'>Byte[]<#else>${field.javaTypeAsString}</#if> ${field.javaName}) {
        this.${field.javaName} = ${field.javaName};
    }

    </#list>
}
