// GENERATED FILE, DO NOT MODIFY! YOUR MODIFICATION WILL BE LOST!
package ${e.packageOfJavaModel};

import java.sql.Timestamp;
import java.math.BigDecimal;

/**
 * ${t.javaName}.
 * <br>${t.comment}
 * <br>Generated from ${t.dbName} database table.
 * <br>Created on: ${e.database.modelCreationDate}
 * <br>Database name: ${e.database.name}
 * <br>Generated by ${appname} v${appversion}
 */
public class ${t.javaName} implements java.io.Serializable {

    <#list t.fieldList as field>
    /* ${field.comment}. Database: ${field.dbName}, ${field.dbType}, <#if field.primaryKey>primary key, </#if><#if field.nullable>not nullable.<#else>nullable.</#if> */
    private ${field.javaTypeAsString} ${field.javaName};
    </#list>

    /** Default constructor. */
    public ${t.javaName}() {}

    /**
     * Constructor.
    <#list t.fieldList as field>
     * @param ${field.javaName} ${field.comment}
    </#list>
     */
    public ${t.javaName}(<#list t.fieldList as field>${field.javaTypeAsString} ${field.javaName}<#if field_has_next>, </#if></#list>) {
        <#list t.fieldList as field>
        this.${field.javaName} = ${field.javaName};
        </#list>
    }

    <#list t.fieldList as field>
    /**
     * ${field.comment}
     * <br>${field.dbName}, ${field.dbType}, <#if field.primaryKey>primary key, </#if><#if field.nullable>not nullable.<#else>nullable.</#if>
     * @return ${field.javaName} value
     */
    public ${field.javaTypeAsString} get${field.javaName?cap_first}() {
        return this.${field.javaName};
    }
    
    /**
     * ${field.comment}
     * <br>${field.dbName}, ${field.dbType}, <#if field.primaryKey>primary key, </#if><#if field.nullable>not nullable.<#else>nullable.</#if>
     * @param ${field.javaName} new value
     */
    public void set${field.javaName?cap_first}(${field.javaTypeAsString} ${field.javaName}) {
        return this.${field.javaName} = ${field.javaName};
    }

    </#list>
}
