DROP DATABASE IF EXISTS sampledb;
CREATE DATABASE sampledb OWNER postgres;

\c sampledb;

-- CUSTOMER TABLE

DROP TABLE IF EXISTS CUS_CUSTOMER CASCADE;

CREATE TABLE CUS_CUSTOMER
(
  CUS_PK numeric(10,0) NOT NULL, -- Customer unique ID
  CUS_ADR_PK numeric(10,0) NOT NULL, -- Customer address ID
  CUS_NAME character varying(90) NOT NULL, -- Customer name
  CUS_EMAIL character varying(60) NOT NULL, -- Customer email
  CUS_TYPE character(30) NOT NULL, -- Customer type: RETAIL, WHOLESALE, GOVERNMENT
  CUS_REG_TS timestamp without time zone NULL, -- Customer registration timestamp
  CUS_LOCKED boolean, -- Customer has locked
  CUS_MODIFICATON_TS timestamp without time zone NULL, -- Customer record modification date
  CONSTRAINT CUS_PK_KEY PRIMARY KEY (CUS_PK),
  CONSTRAINT CUS_NAME_KEY UNIQUE (CUS_NAME),
  CONSTRAINT CUS_EMAIL_KEY UNIQUE (CUS_EMAIL)
)
WITH (
  OIDS=FALSE
);
ALTER TABLE CUS_CUSTOMER OWNER TO postgres;
COMMENT ON TABLE CUS_CUSTOMER IS 'Customer table';
COMMENT ON COLUMN CUS_CUSTOMER.CUS_PK IS 'Customer unique ID';
COMMENT ON COLUMN CUS_CUSTOMER.CUS_ADR_PK IS ''; -- example of the wrong commenting (mistyped field name): see metadata.txt 'FIXME: Warning: There is no comment in database!'
COMMENT ON COLUMN CUS_CUSTOMER.CUS_NAME IS 'Customer name';
COMMENT ON COLUMN CUS_CUSTOMER.CUS_EMAIL IS ''; -- missing table comment
COMMENT ON COLUMN CUS_CUSTOMER.CUS_TYPE IS 'Customer type: RETAIL, WHOLESALE, GOVERNMENT';
COMMENT ON COLUMN CUS_CUSTOMER.CUS_REG_TS IS 'Customer registration timestamp';
COMMENT ON COLUMN CUS_CUSTOMER.CUS_LOCKED IS 'Customer has locked';
COMMENT ON COLUMN CUS_CUSTOMER.CUS_MODIFICATON_TS IS 'Customer record modification date';

DROP SEQUENCE IF EXISTS SEQ_CUS_CUSTOMER_CUS_PK;

CREATE SEQUENCE SEQ_CUS_CUSTOMER_CUS_PK
   INCREMENT 1
   START 1
   MINVALUE 1;
ALTER TABLE SEQ_CUS_CUSTOMER_CUS_PK OWNER TO postgres;
COMMENT ON SEQUENCE SEQ_CUS_CUSTOMER_CUS_PK IS 'Customer pk sequence';

-- ADDRESS TABLE

DROP TABLE IF EXISTS ADR_ADDRESS CASCADE;

CREATE TABLE ADR_ADDRESS
(
  ADR_PK numeric(10,0) NOT NULL, -- Address unique ID
  ADR_STREET character varying(90) NOT NULL, -- Address street part: HOUSE_NUMBER STREET_NAME [STREET_TYPE] [STREET_DIRECTION] [BUILDING] [FLOOR] [APARTMENT]
  ADR_LOCALITY character varying(40) NOT NULL, -- Adress locality, e.g: WASHINGTON DC
  ADR_POSTAL_CODE character(20) NOT NULL, -- Address postal code, e.g: 20008 
  ADR_COUNTRY character(40), -- Address Country
  ADR_LOCKED boolean, -- Address has locked
  ADR_MODIFICATON_TS timestamp without time zone NULL, -- Address record modification date
  CONSTRAINT ADR_PK_KEY PRIMARY KEY (ADR_PK)
)
WITH (
  OIDS=FALSE
);
ALTER TABLE ADR_ADDRESS OWNER TO postgres;
COMMENT ON TABLE ADR_ADDRESS IS 'Address table';
COMMENT ON COLUMN ADR_ADDRESS.ADR_PK IS 'Address unique ID';
COMMENT ON COLUMN ADR_ADDRESS.ADR_STREET IS 'Address street part: HOUSE_NUMBER STREET_NAME [STREET_TYPE] [STREET_DIRECTION] [BUILDING] [FLOOR] [APARTMENT]';
COMMENT ON COLUMN ADR_ADDRESS.ADR_LOCALITY IS 'Adress locality, e.g: WASHINGTON DC';
COMMENT ON COLUMN ADR_ADDRESS.ADR_POSTAL_CODE IS ''; -- missing table comment
COMMENT ON COLUMN ADR_ADDRESS.ADR_COUNTRY IS 'Address CountryT';
COMMENT ON COLUMN ADR_ADDRESS.ADR_LOCKED IS 'Customer has locked';
COMMENT ON COLUMN ADR_ADDRESS.ADR_MODIFICATON_TS IS 'Address record modification date';

DROP SEQUENCE IF EXISTS SEQ_ADR_ADDRESS_ADR_PK;

CREATE SEQUENCE SEQ_ADR_ADDRESS_ADR_PK
   INCREMENT 1
   START 1
   MINVALUE 1;
ALTER TABLE SEQ_ADR_ADDRESS_ADR_PK OWNER TO postgres;
COMMENT ON SEQUENCE SEQ_ADR_ADDRESS_ADR_PK IS 'Address pk sequence';


-- CREATING INDEXES


CREATE INDEX ON CUS_CUSTOMER (CUS_NAME);
CREATE INDEX ON CUS_CUSTOMER (CUS_EMAIL);
CREATE INDEX ON ADR_ADDRESS (ADR_LOCALITY);
CREATE INDEX ON ADR_ADDRESS (ADR_POSTAL_CODE);


-- INSERT ADDRESS


INSERT INTO ADR_ADDRESS (ADR_PK, ADR_STREET, ADR_LOCALITY, ADR_POSTAL_CODE, ADR_COUNTRY, ADR_LOCKED, ADR_MODIFICATON_TS)
    values (nextval('SEQ_ADR_ADDRESS_ADR_PK'), '1145 17th St NW', 'WASHINGTON DC', '20036', 'USA', false, now());
INSERT INTO ADR_ADDRESS (ADR_PK, ADR_STREET, ADR_LOCALITY, ADR_POSTAL_CODE, ADR_COUNTRY, ADR_LOCKED, ADR_MODIFICATON_TS)
    values (nextval('SEQ_ADR_ADDRESS_ADR_PK'), '600 Maryland Ave SW', 'WASHINGTON DC', '20002', 'USA', false, now());
INSERT INTO ADR_ADDRESS (ADR_PK, ADR_STREET, ADR_LOCALITY, ADR_POSTAL_CODE, ADR_COUNTRY, ADR_LOCKED, ADR_MODIFICATON_TS)
    values (nextval('SEQ_ADR_ADDRESS_ADR_PK'), '736 Sicard St SE', 'WASHINGTON DC', '20374', 'USA', false, now());

    
-- INSERT CUSTOMER


INSERT INTO CUS_CUSTOMER (CUS_PK, CUS_ADR_PK, CUS_NAME, CUS_EMAIL, CUS_TYPE, CUS_REG_TS, CUS_LOCKED, CUS_MODIFICATON_TS)
    values (nextval('SEQ_CUS_CUSTOMER_CUS_PK'), 1, 'Jack Daniels', 'jack.daniels@earth.sun', 'RETAIL', now(), false, now());
INSERT INTO CUS_CUSTOMER (CUS_PK, CUS_ADR_PK, CUS_NAME, CUS_EMAIL, CUS_TYPE, CUS_REG_TS, CUS_LOCKED, CUS_MODIFICATON_TS)
    values (nextval('SEQ_CUS_CUSTOMER_CUS_PK'), 2, 'John Python', 'john.python@venus.sun', 'WHOLESALE', now(), true, now());
INSERT INTO CUS_CUSTOMER (CUS_PK, CUS_ADR_PK, CUS_NAME, CUS_EMAIL, CUS_TYPE, CUS_REG_TS, CUS_LOCKED, CUS_MODIFICATON_TS)
    values (nextval('SEQ_CUS_CUSTOMER_CUS_PK'), 3, 'Jessie Java', 'jessie.java@mars.sun', 'GOVERNMENT', now(), false, now());
