name: Test
on:
  push:
    branches: [master]

jobs:
  vm-job:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        # Provide the password for postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: sample
          POSTGRES_PORT: 5432
          PGPASSWORD: sample
        ports:
          - 5432:5432
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 10s
          --health-retries 5

    steps:
      # Downloads a copy of the code in your repository before running CI tests
      - name: Check out repository code
        uses: actions/checkout@v2

      # Performs a clean installation of all dependencies in the `package.json` file
      # For more information, see https://docs.npmjs.com/cli/ci.html
      - name: Init Database
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: sample
          POSTGRES_PORT: 5432
          PGPASSWORD: sample
        run: netstat -nlp | grep 5432 && ls -l && psql -h 0.0.0.0 -p 5432 -U postgres -a -f ./easydao-samples/creating-sampledb/initdb.sql

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Test maven
        run: mvn -v

      - name: Install JDBC ojdbc5
        run: mvn install:install-file -Dfile=./ojdbc5-11.1.0.7.0.jar -DgroupId=com.oracle -DartifactId=ojdbc5 -Dversion=11.1.0.7.0 -Dpackaging=jar

      - name: Install JDBC ora18n
        run: mvn install:install-file -Dfile=./orai18n-11.1.0.7.0.jar -DgroupId=com.oracle -DartifactId=orai18n -Dversion=11.1.0.7.0 -Dpackaging=jar

      - name: Running test
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: sample
          POSTGRES_PORT: 5432
          PGPASSWORD: sample
        run: mvn clean install
       
      - name: Notify slack success
        if: success()
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_TITLE: Success
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}

      - name: Notify slack fail
        if: failure()
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_TITLE: Error
          SLACK_COLOR: '#3278BD'
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
